[project]
name = "mcp-prac"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-anthropic>=0.3.13",
    "langchain-groq>=0.3.2",
    "mcp-use>=1.2.12",
]
